const array = [0,1,2,3,4,5];
const newarray = array.join()
array.push("abhi")
array.pop("abhi")
array.unshift(0)
array.shift(0)
console.log(array)
console.log(array.includes("Abhishek"))
console.log(array.indexOf(5))
console.log(newarray)
console.log(typeof array)
console.log(typeof newarray)
console.log(array)
console.log(array.slice(1,4))
console.log(array)
console.log(array.splice(1,4))
console.log(array)